### ISSUE TITLE
Generate a domain with AI Search

### ISSUE THREAD

**Issue by 10corp** [centralnicgroup-opensource/rtldev-middleware-blesta#211]
Adding a feature like "Generate a domain with AI" can be an excellent addition to your service offering, especially for businesses looking to establish an online presence.

**Comment by KaiSchwarz-cnic** [comment]
@10corp thanks for addressing, but as we are not the developers of Blesta itself, we can't do much.
The built-in domain search of Blesta is maintained by team Blesta itself, please reach out to them in that regard.

If you do not agree (maybe I missed something), please follow-up and I'll reopen this github issue.

Kind Regards

**Comment by KaiSchwarz-cnic** [comment]
for reference: our module integrates the `checkAvailability` function, but the purposes of it is not about creating domain name suggestions, but checking availability of domains. If Blesta would add support for Domain Name Suggestions so that registrars can integrate that feature, then we would have a chance (while there's right now no official feature yet available on our Backend API-side. WIP for now).
